/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": process.env.GATSBY_AWS_PROJECT_REGION,
    "aws_appsync_graphqlEndpoint": process.env.GATSBY_AWS_APPSYNC_GRAPHQLENDPOINT,
    "aws_appsync_region": process.env.GATSBY_AWS_APPSYNC_REGION,
    "aws_appsync_authenticationType": process.env.GATSBY_AWS_APPSYNC_AUTHENTICATIONTYPE,
    "aws_appsync_apiKey": process.env.GATSBY_AWS_APPSYNC_APIKEY,
    "aws_cognito_identity_pool_id": process.env.GATSBY_AWS_COGNITO_IDENTITY_POOL_ID,
    "aws_cognito_region": process.env.GATSBY_AWS_COGNITO_REGION,
    "aws_user_pools_id": process.env.GATSBY_AWS_USER_POOLS_ID,
    "aws_user_pools_web_client_id": process.env.GATSBY_AWS_USER_POOLS_WEB_CLIENT_ID,
    "oauth": process.env.GATSBY_OAUTH 
};


export default awsmobile;
